import numpy as np
import pandas as pd
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv1D, MaxPooling1D, Flatten, Dense, Dropout, BatchNormalization
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import to_categorical
from sklearn.model_selection import train_test_split
from Bio import SeqIO

# --- A NOTE ON LABELS ---
# Since we don't have true labels, we'll create dummy labels based on abundance.

print("Loading and preparing data...")

# 1. Load the data generated by Person 1
# <<< THIS IS THE CORRECTED PART >>>
# We are changing how the ASV table is loaded to match its format.
asv_table = pd.read_csv('ASV_table.csv', index_col=0)
# We rename the column to something standard like 'abundance'
asv_table.columns = ['abundance']
sequences = {record.id: str(record.seq) for record in SeqIO.parse("ASVs.fasta", "fasta")}

# 2. Create dummy labels (0 for rare, 1 for common)
median_abundance = asv_table['abundance'].median()
# The ASV IDs are now in the index of the table
labels = {asv_id: 1 if count > median_abundance else 0 for asv_id, count in asv_table['abundance'].items()}

# Match sequences to their new labels
dna_sequences = []
numeric_labels = []
# The FASTA headers are ASV_1, ASV_2, etc. We need to match them to the full DNA sequences in the table index.
# We will create a mapping from the full sequence to the simple ASV_# ID.
seq_to_id_map = {str(record.seq): record.id for record in SeqIO.parse("ASVs.fasta", "fasta")}

for seq, count in asv_table['abundance'].items():
    if seq in seq_to_id_map:
        asv_id = seq_to_id_map[seq]
        dna_sequences.append(seq)
        numeric_labels.append(1 if count > median_abundance else 0)

# 3. Pre-process the DNA sequences: One-Hot Encoding
mapping = {'A': [1, 0, 0, 0], 'C': [0, 1, 0, 0], 'G': [0, 0, 1, 0], 'T': [0, 0, 0, 1], 'N': [0,0,0,0]}
encoded_sequences = [[mapping.get(base, [0,0,0,0]) for base in seq] for seq in dna_sequences]

# Pad sequences to the same length for the model
max_len = max(len(seq) for seq in encoded_sequences)
X = pad_sequences(encoded_sequences, maxlen=max_len, padding='post', dtype='float32')
y = to_categorical(np.array(numeric_labels)) 

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"Data prepared. Training data shape: {X_train.shape}")

# 4. Build the 1D CNN model
model = Sequential([
    Conv1D(filters=32, kernel_size=12, activation='relu', input_shape=X_train.shape[1:]),
    BatchNormalization(),
    MaxPooling1D(pool_size=4),
    Dropout(0.2),
    
    Flatten(),
    
    Dense(16, activation='relu'),
    Dropout(0.5),
    
    Dense(y.shape[1], activation='softmax') # Use number of classes for output
])

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.summary()

# 5. Train the model
print("\nStarting model training...")
model.fit(X_train, y_train, epochs=20, batch_size=16, validation_data=(X_test, y_test), verbose=2)

# 6. Save the final model
model.save('dl_model.h5')
print("\nTraining complete! Model has been saved as dl_model.h5")